### PR TITLE
Attempt to fix formatting in citation

### PR DESCRIPTION
**Pull request by kahinimehta**
Fix Citation by moving away from pybtex?

### CODE REVIEW

**Comment by tsalo** [comment]
Mostly looks good. Just a couple of small things. I'm not familiar with NLM, so I just compared against the PubMed citations.

Here's the one from the HTML:
> Covitz, S, Tapera, TM, Adebimpe, A, Alexander-Bloch, AF, Bertolero, MA, Feczko, E, Franco, AR, Gur, RE, Gur, RC &  Hendrickson, T. Curation of BIDS (CuBIDS): A workflow and software package for streamlining reproducible curation of large BIDS datasets. <em>NeuroImage</em>. 2022.

Here's the one from PubMed:

> Covitz S, Tapera TM, Adebimpe A, Alexander-Bloch AF, Bertolero MA, Feczko E, Franco AR, Gur RE, Gur RC, Hendrickson T, Houghton A, Mehta K, Murtha K, Perrone AJ, Robert-Fitzgerald T, Schabdach JM, Shinohara RT, Vogel JW, Zhao C, Fair DA, Milham MP, Cieslak M, Satterthwaite TD. Curation of BIDS (CuBIDS): A workflow and software package for streamlining reproducible curation of large BIDS datasets. Neuroimage. 2022 Nov;263:119609. doi: 10.1016/j.neuroimage.2022.119609. Epub 2022 Sep 3. PMID: 36064140; PMCID: PMC9981813.

- There shouldn't be commas between last names and initials.
- Missing comma between second-to-last author and ampersand.
- Extra space after ampersand.

**Comment by tsalo** [comment]
That looks really good! It does look like the CuBIDS entry is missing some authors though.

**Comment by kahinimehta** [comment]
Ahh @tsalo - I think that is due to how the .bib file is populated. Is there a way to edit this?

**Comment by kahinimehta** [comment]
The .bib file just says "and others" after a certain number of authors

**Comment by tsalo** [comment]
You'll need to directly edit the .bib file in that case.

**Comment by tsalo** [comment]
LGTM! Merging.

**Pull request merged**
